{"uuid": "aeed96f2-cfc0-45b0-9f81-c5d8fbabb3aa", "children": ["084e22b9-056b-4e28-8bc3-2e0a03c725ab"], "befores": [{"name": "setup", "status": "failed", "statusDetails": {"message": "AssertionError: User icon is not presented\n", "trace": "  File \"/Users/larisayusina/Desktop/environments/selenium_env/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/larisayusina/Desktop/environments/selenium_env/lib/python3.9/site-packages/_pytest/fixtures.py\", line 918, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/larisayusina/Desktop/environments/selenium_env/lib/python3.9/site-packages/_pytest/fixtures.py\", line 778, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/larisayusina/Desktop/stepik_lessons/module_5/test_product_page.py\", line 75, in setup\n    self.page.should_be_authorized_user()\n  File \"/Users/larisayusina/Desktop/stepik_lessons/module_5/pages/base_page.py\", line 67, in should_be_authorized_user\n    assert self.is_element_present(*LoginPageLocators.USER_ICON), \"User icon is not presented\"\n"}, "start": 1624565339363, "stop": 1624565355712}], "start": 1624565339363, "stop": 1624565355717}